name: integration-tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run react:start 
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: 59bd453f-26d8-40fc-81b8-78c498a449f4
